name        : libdv
version     : 1.0.0
release     : 2
source      :
    - https://netix.dl.sourceforge.net/project/libdv/libdv/1.0.0/libdv-1.0.0.tar.gz : a305734033a9c25541a59e8dd1c254409953269ea7c710c39e540bd8853389ba
homepage    : http://libdv.sourceforge.net/
license     : GPL-2.0
component   :
    - multimedia.codecs
    - devel: programming.devel
    - utils: multimedia.video
summary     :
    - Quasar DV codec, common for digital camcorders
    - devel: Development files for libdv
    - utils: ommand line utilities for libdv
description :
    - The Quasar DV codec (libdv) is a software codec for DV video, the encoding format used by most digital camcorders, typically those that support the IEEE 1394 (a.k.a. FireWire or i.Link) interface.
    - devel: Development files for libdv
    - utils: ommand line utilities for libdv
builddeps  :
    - pkgconfig(popt)
patterns   :
    - utils:
        - /usr/bin
        - /usr/share
setup      : |
    %configure --disable-static --disable-xv
build      : |
    %make
install    : |
    %make_install
